title: Apache Spark 
description: DataFrame, Dataset and Spark SQL API's
show_downloads: true
google_analytics:
# theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  zip_url: http://example.com/download.zip
  repository_url: https://vijaypavann.github.io/apache-spark
